# Generated by Django 3.0.8 on 2020-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_posted',
            field=models.CharField(default='0000-00-00', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='Enjoy!'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Video', max_length=150),
        ),
    ]
