# Generated by Django 3.0.8 on 2020-08-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200804_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='000000000000000', max_length=150),
        ),
    ]
