# Generated by Django 3.0.8 on 2020-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='none', max_length=150),
        ),
    ]
