# Generated by Django 3.0.8 on 2020-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='https://i.ytimg.com/vi/7NpvXBM4-1A/mqdefault.jpg', max_length=50),
        ),
    ]
