# Generated by Django 3.0.8 on 2020-08-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20200810_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='none', max_length=150),
        ),
    ]
